"""Updated founded database column

Revision ID: 9c6d10e9b4ad
Revises: e25d494f9e37
Create Date: 2024-08-08 22:24:25.409448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6d10e9b4ad'
down_revision = 'e25d494f9e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('founded',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('founded',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
