"""Removed nullable=true from transactions for portfolios

Revision ID: 53e6190940ef
Revises: ab3455450be7
Create Date: 2024-08-16 12:39:18.753143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e6190940ef'
down_revision = 'ab3455450be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
