"""update stock table

Revision ID: 5ccfb0f71fba
Revises: 609de1d8b78c
Create Date: 2024-08-10 20:06:06.972546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccfb0f71fba'
down_revision = '609de1d8b78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('current_price',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('price_earnings_ratio',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('high_today',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('low_today',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('open_price',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('fifty_two_week_high',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('fifty_two_week_low',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('fifty_two_week_low',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('fifty_two_week_high',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('open_price',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('low_today',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('high_today',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('price_earnings_ratio',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('current_price',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
